hello world

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,3 +1,12 @@
 #!/bin/bash
-python3 $PYFILE
+
+# Check if PYFILE variable is set
+if [ -z "$PYFILE" ]; then
+    echo "Error: The environment variable \$PYFILE is not set."
+    exit 1
+fi
+
+# Run the Python script
+python3 "$PYFILE"
+
 
