hello world

diff --git a/0x00-python-hello_world/1-run_inline b/0x00-python-hello_world/1-run_inline
--- a/0x00-python-hello_world/1-run_inline
+++ b/0x00-python-hello_world/1-run_inline
@@ -1,3 +1,11 @@
-#!bin/bash
-python3 <<< $PYCODE
-export PYCODE='print(f"Best School: {88+10}")'
+#!/bin/bash
+
+# Check if PYCODE variable is set
+if [ -z "$PYCODE" ]; then
+    echo "Error: The environment variable \$PYCODE is not set."
+    exit 1
+fi
+
+# Run the Python code
+python3 -c "$PYCODE"
+
